### Create a new Project
POST https://pmspa-api.herokuapp.com/v1/projects
Content-Type: application/json
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQzMjE2NmQ0NzdkOTAyYjU1ZjZkYWMiLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE0ODE2MDg3OTA5MDQtNmI0N2M4OGU1YjAwP2l4bGliPXJiLTEuMi4xJnE9ODAmZm09anBnJmNyb3A9ZW50cm9weSZjcz10aW55c3JnYiZ3PTE1MCZoPTE1MCZmaXQ9Y3JvcCZpeGlkPWV5SmhjSEJmYVdRaU9qRjkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1ODA3MTQzNDAsImV4cCI6MTU4MDgwMDc0MH0.OuwuACuHvjMHuklfjM744kTbT28AhZNR958xTExGf8Y; Path=/; HttpOnly; Secure; SameSite=None

{
  "title": "AllGood",
  "description": "AllGood Diapers."
}

### Get all projects
GET  https://pmspa-api.herokuapp.com/v1/projects
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQzMjE2NmQ0NzdkOTAyYjU1ZjZkYWMiLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE0ODE2MDg3OTA5MDQtNmI0N2M4OGU1YjAwP2l4bGliPXJiLTEuMi4xJnE9ODAmZm09anBnJmNyb3A9ZW50cm9weSZjcz10aW55c3JnYiZ3PTE1MCZoPTE1MCZmaXQ9Y3JvcCZpeGlkPWV5SmhjSEJmYVdRaU9qRjkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1ODA3MTQzNDAsImV4cCI6MTU4MDgwMDc0MH0.OuwuACuHvjMHuklfjM744kTbT28AhZNR958xTExGf8Y; Path=/; HttpOnly; Secure; SameSite=None

### Delete project
DELETE  https://projectmanager-prod.herokuapp.com/v1/projects/5d5975b85082662b5fbbe83b

### Login route
POST  https://projectmanager-prod.herokuapp.com/v1/auth/login
Content-Type: application/json

{
  "email": "marko@angelovski.ga",
  "password": "maderfaker"
}