### Create a new link
POST http://localhost:3000/v1/links/5ddb2f98a4c9183c3968c64a
Content-Type: application/json
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGRiMmYyYmE0YzkxODNjMzk2OGM2NDkiLCJlbWFpbCI6Imd1ZXN0MUBndWVzdDEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE1NzQ2NDU3MDMsImV4cCI6MTU3NDczMjEwM30.0cj0wZ99fgm0jCmwtjnYAI_9Uor5ZHYkFtH17Z36qCM
#Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzQ2NDgxOTYsImV4cCI6MTU3NDczNDU5Nn0.r-GOLyJcBzkxVlmHfFclz_rf-2LevDaxvhLCRVBRpy0

{
  "title": "Matrica",
  "link": "https://drive.google.com"
}

### Patch a link: /links/:linkId?link={URI-encoded-values}
//{URI-encoded-values} === [{"propName":"name1","value":"value1"},{"propName":"name2","value":"value2"}]
PATCH  http://localhost:3000/links/5db4860abd41f338d20416c0?link=%5B%7B%22propName%22%3A%22title%22%2C%22value%22%3A%22Ne%C5%A1to%22%7D%2C%7B%22propName%22%3A%22link%22%2C%22value%22%3A%22bbb%22%7D%5D

### Delete a link: /links/{taskId}/?linkId={linkId}
DELETE  http://localhost:3000/v1/links/5ddc2301504af2642c4b5588?linkId=5ddc232c504af2642c4b5589
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGRiMmYyYmE0YzkxODNjMzk2OGM2NDkiLCJlbWFpbCI6Imd1ZXN0MUBndWVzdDEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE1NzQ3MDgyNDksImV4cCI6MTU3NDc5NDY0OX0.q8KUAixZ71nL_vqiy6chmy3P3Y66xbL0eoNUFgN4QRI

