### Create a new Project
POST http://localhost:3000/projects
Content-Type: application/json

{
  "title": "Nešto manje novi projekt",
  "description": "Opis nešto manje novog projekta."
}
### Get all projects
GET  http://localhost:3000/projects

### Delete project
DELETE  http://localhost:3000/projects/5d5975b85082662b5fbbe83b