### Create a new Project
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Task 3",
  "description": "Opis taska 3",
  "column": "Completed",
  "dueDate": 1577836800000,
  "project": "5d598db65082662b5fbbe853"
}
### Get all tasks
GET  http://localhost:3000/tasks