### Create a new Project
POST http://localhost:3000/v1/projects
Content-Type: application/json
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzQ2MTQzNjgsImV4cCI6MTU3NDcwMDc2OH0.uuBXG_4IFDh5bNPsygfYwb0SSgrLp4oySuFG63t8vcQ

{
  "title": "Nešto manje novi projekt",
  "description": "Opis nešto manje novog projekta."
}

### Get all projects
GET  http://localhost:3000/v1/projects
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGRiMmYyYmE0YzkxODNjMzk2OGM2NDkiLCJlbWFpbCI6Imd1ZXN0MUBndWVzdDEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE1NzQ2NDU3MDMsImV4cCI6MTU3NDczMjEwM30.0cj0wZ99fgm0jCmwtjnYAI_9Uor5ZHYkFtH17Z36qCM

### Delete project
DELETE  http://localhost:3000/v1/projects/5d5975b85082662b5fbbe83b

### Login route
POST  http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "email": "marko@angelovski.ga",
  "password": "maderfaker"
}