### Create a new Task
POST http://localhost:3000/v1/tasks
Content-Type: application/json
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE0ODE2MDg3OTA5MDQtNmI0N2M4OGU1YjAwP2l4bGliPXJiLTEuMi4xJnE9ODAmZm09anBnJmNyb3A9ZW50cm9weSZjcz10aW55c3JnYiZ3PTE1MCZoPTE1MCZmaXQ9Y3JvcCZpeGlkPWV5SmhjSEJmYVdRaU9qRjkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1Nzk0MzAzMjgsImV4cCI6MTU3OTUxNjcyOH0.s4d2QzRiHS2aoyS4v3OQ1mp0RwXSrJWx8ED5kzEG_hU

{
  "title": "Crna Mačka",
  "description": "Opis taska 3",
  "column": "Completed",
  "dueDate": 1577836800000,
  "project": "5de06639dcaabc585f230340"
}

### Get all tasks
GET  http://localhost:3000/v1/tasks
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE0ODE2MDg3OTA5MDQtNmI0N2M4OGU1YjAwP2l4bGliPXJiLTEuMi4xJnE9ODAmZm09anBnJmNyb3A9ZW50cm9weSZjcz10aW55c3JnYiZ3PTE1MCZoPTE1MCZmaXQ9Y3JvcCZpeGlkPWV5SmhjSEJmYVdRaU9qRjkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzkwNDk1MzQsImV4cCI6MTU3OTEzNTkzNH0.JB83a79JQ9D33Nlrdg3vp8sd4N0vrLrJZn6nPYpCs24

### Update task
PATCH http://localhost:3000/v1/tasks/5ddb2ff0a4c9183c3968c64d
Content-Type: application/json
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzQ2NDY2NDEsImV4cCI6MTU3NDczMzA0MX0.dBu6Vw7bdjYbV2hBsoSCvLTTnDgfIR9Rq8LL32aiEqs

[
  {
  "propName": "title",
  "value": "Naslov promijenjen jednom"
  },
  {
  "propName": "column",
  "value": "Upcoming"
  }
]

### Delete task
DELETE  http://localhost:3000/v1/tasks/5ddb2ff0a4c9183c3968c64d
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGRiMmYyYmE0YzkxODNjMzk2OGM2NDkiLCJlbWFpbCI6Imd1ZXN0MUBndWVzdDEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE1NzQ2NDU3MDMsImV4cCI6MTU3NDczMjEwM30.0cj0wZ99fgm0jCmwtjnYAI_9Uor5ZHYkFtH17Z36qCM
