### Get all users route
GET http://localhost:3000/v1/auth

### Auth check
POST http://localhost:3000/v1/auth
Cookie: uth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzQ2NDU0NzMsImV4cCI6MTU3NDczMTg3M30.2k6S9mToE5gz9au-sJPDUDE5dG3MzWfJ7CxYAzhyZSw

### Register route
POST  http://localhost:3000/v1/auth/register
Content-Type: application/json
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzQ4OTQ2MzEsImV4cCI6MTU3NDk4MTAzMX0.Bh6b8Zi5fNUgTQqF9x5-vKhffIaVfSFaYRUaqP2_TKE
#Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGRiMmYyYmE0YzkxODNjMzk2OGM2NDkiLCJlbWFpbCI6Imd1ZXN0MUBndWVzdDEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE1NzQ4OTQ5MDQsImV4cCI6MTU3NDk4MTMwNH0.G5DH_LcNCHEtt7fI5EoI3kmJg9OBe50hS8PT5OTCotQ

{
  "email": "guest2@guest2.com",
  "password": "guest2"
}

### Login route
POST  http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "email": "marko@angelovski.ga",
  "password": "maderfaker"
}

### Logout user route
GET http://localhost:3000/v1/auth/logout
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9pbWFnZXMudW5zcGxhc2guY29tL3Bob3RvLTE0ODE2MDg3OTA5MDQtNmI0N2M4OGU1YjAwP2l4bGliPXJiLTEuMi4xJnE9ODAmZm09anBnJmNyb3A9ZW50cm9weSZjcz10aW55c3JnYiZ3PTE1MCZoPTE1MCZmaXQ9Y3JvcCZpeGlkPWV5SmhjSEJmYVdRaU9qRjkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NzU1MTY0MDYsImV4cCI6MTU3NTYwMjgwNn0.4kEUnExHs1MzyhU7oeNZa1ZDO3H1xFVpeB5mmfM0eeQ

### Update user route
PATCH http://localhost:3000/v1/auth/update-profile
Cookie: auth=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NjA4MDdmNTlkZjM5YTE0NjFlMDciLCJlbWFpbCI6Im1hcmtvQGFuZ2Vsb3Zza2kuZ2EiLCJyb2xlIjoidXNlciIsImlhdCI6MTU3NDAwOTMxMSwiZXhwIjoxNTc0MDk1NzExfQ.GpfdqvriS6rUhU49QEuF0PJ23VBtOI1KPR6Vml73wRM



