### Create a new note
POST https://projectmanager-stage.herokuapp.com/notes/5dbda8da86838336f54c84ba
Content-Type: application/json

{
  "note": "neš note!"
}

### Patch a note: /notes/:noteId?note={URI-encoded-values}
PATCH  https://projectmanager-stage.herokuapp.com/notes/5dbdb9a819b3c03c44710055?note=nota%20bene

### Delete a note: /notes/{taskId}/?noteId={noteId}
DELETE  https://projectmanager-stage.herokuapp.com/notes/5dbda8da86838336f54c84ba?noteId=5dbdadd186838336f54c84c0

